version: '3'

services:
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-app
    expose:
      - 3000
    #volumes:
    #  - /home/ubuntu/secretzoo/frontend/client:/usr/src/app
    #volumes:
    #  - /usr/src/app:/usr/share/nginx/html
    environment:
      - WDS_SOCKET_PROT=0
      - REACT_APP_SOCKET_SERVER_URL=ws://node-server:3001
      - APPLICATION_SERVER_URL=https://openvidu.secretzoo.site
      # - APPLICATION_SERVER_URL=http://localhost:5442
    networks:
      - docker_nat

  node-server:
      build:
        context: ./server
        dockerfile: Dockerfile # Node.js 서버를 위한 Dockerfile
      container_name: node-server
      expose:
        - 3001
      restart: always
      networks:
        - docker_nat
networks:
  docker_nat:
    external: true