version: '3'

services:
  react-app:
    build:
      context: /client
      dockerfile: Dockerfile
    container_name: react-app
    # ports:
    #  - "3000:3000"
    #volumes:
    #  - /home/ubuntu/secretzoo/frontend/client:/usr/src/app
    #volumes:
    #  - /usr/src/app:/usr/share/nginx/html
    networks:
      - docker_nat

  node-server:
      build:
        context: /server
        dockerfile: Dockerfile # Node.js 서버를 위한 Dockerfile
      container_name: node-server
      ports:
      - "3001:3001" # Node.js 서버 포트 설정
      networks:
        - docker_nat
networks:
  docker_nat:
    external: true