FROM openjdk:17-alpine


ARG JAR_FILE=ranking-0.0.1-SNAPSHOT.jar

# 호스트의 JAR 파일을 컨테이너로 복사
COPY ${JAR_FILE} myboot.jar

# 실행시 사용할 환경 변수 설정 (예: 프로파일 설정)
ENV SPRING_PROFILES_ACTIVE=docker

ENTRYPOINT ["java", "-jar", "/myboot.jar"]
