FROM mysql:latest

# 환경 변수 설정 (예: 데이터베이스 이름, 사용자, 비밀번호)
ENV MYSQL_DATABASE=rank_db \
    MYSQL_USER=ssafy \
    MYSQL_PASSWORD=ssafy \
    MYSQL_ROOT_PASSWORD=ssafy

# 포트 설정 (기본 MySQL 포트는 3306)
EXPOSE 3306
