# Redis base image
FROM redis:latest

# Expose the default Redis port
EXPOSE 6379

# Set a custom configuration if needed
# COPY redis.conf /etc/redis/redis.conf
# CMD ["redis-server", "/etc/redis/redis.conf"]

